config/routes.rb
Rails.application.routes.draw do

  match 'visitando/:id', to: 'urls#visitando', via: 'get', as: 'visitlong'

  root 'welcome#index'

  get 'login', to: 'users#login'

  post'ingresando', to: 'users#authenticate' 

  get 'ingresando', to: 'users#login'

  get 'users', to: 'users#new'

  get 'logout', to: 'users#logout'

  resources :users , except: :index

  resources :urls, only: [:new, :create, :show, :destroy]

  

end

app/models/url.rb
class Url < ActiveRecord::Base

  belongs_to :user

  validate :valid_url
  # validates_format_of :long_url, :with => URI::regexp(%w(http https))

  def valid_url
    slash = Regexp.escape('//')

    regex = /\Ahttps:#{Regexp.escape('//')}/

    unless long_url =~ /\Ahttps:#{Regexp.escape('//')}/ || long_url =~ /\Ahttp:#{Regexp.escape('//')}/
      errors.add(:long_url, "No ingresaste una URL")
    end
  end

  def self.generate_url
    letras = ('a'..'z').to_a
    numeros = (1..9).to_a
    url = ''

    for i in 1..8
      random_n = rand(0..8)
      random_l = rand(0..25)

      if i >= 1 && i <= 3
        #Tres letras minusculas
        url += letras[random_l]
      elsif i >= 4 && i <= 5
        #Dos numeros
        url += numeros[random_n].to_s
      elsif i >= 6 && i <= 7
        #Dos letras mayusculas
        url += letras[random_l].upcase
      elsif i == 8 
        #Un numero
        url += numeros[random_n].to_s
      end 
    end
    url.strip
  end

  # def ini_uri
  #   'http://sho.di/'
  # end
  
end

app/models/user.rb
class User < ActiveRecord::Base

  validates :name, presence: { message: 'Tienes que ingresar tu nombre' } 
  validates :email, presence: { message: 'Tienes que ingresar tu email' }
  validates :password, presence: { message: 'Tienes que ingresar una contraseña' }
  validates :email,  uniqueness: { message: 'El email ya fue registrado' }

  include BCrypt

  has_many :urls

  def password
    @password ||= Password.new(password_digest)
  end

  def password=(user_password)
    @password = Password.create(user_password)
    self.password_digest = @password
  end

  def self.authenticate(email, user_password)
    user = User.find_by(email: email)
    if user && (user.password == user_password)
      return user
    else
      nil
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


end

app/controllers/urls_controller.rb
class UrlsController < ApplicationController
  include ApplicationHelper
  def new
    @url = Url.new 
  end

  def create
    long_url = params[:url][:long_url]
    short_url = Url.generate_url
    # current_user
    
    @new_url = Url.new(long_url: long_url, short_url: short_url)

    if @new_url.save
      if current_user
        current_user.urls << @new_url
        # Recargando con ajax
        redirect_to user_path(current_user)
      else
        redirect_to :root
      end
    else
      @new_url.errors
    end
  end

  def visitando
    url_id = params[:id]
    ruta = Url.find(url_id)
    visitas = ruta.visits + 1
    ruta.update(visits: visitas )
    redirect_to ruta.long_url
    # render nothing: true
    # if redirect_to url.long_url
    #   visitas = url.visits + 1
    #   url.update(visits: visitas )
    # end
  end

  # def lala
  #   url_id = params[:id]
  #   p ruta = Url.find(url_id)
  #   puts "****************************"
  #   puts "before"
  #   visitas = ruta.visits + 1
  #   ruta.update(visits: visitas )
  #   puts "after"
  #   p ruta.visits
  #   # render nothing: true

  #   redirect_to ruta.long_url
  # end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def login
    @user = User.new
  end

  def authenticate

    email = params['user']['email']
    password = params['user']['password']

    if User.authenticate(email, password)
      @user = User.authenticate(email, password)
      session[:id] = @user.id
      redirect_to(@user)
    else
      @user = User.new
      #flash[:error] = "El email o password es incorrecto"
      @error = "El email o password es incorrecto"
      render :login
    end

  end

  def show
    @user = User.find(params['id']);
    @urls_user = @user.urls
  end

  def new
    @user = User.new  
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:id] = @user.id
      redirect_to(@user)
    else
      @errors = @user.errors.messages
      @user = User.new
      render :new
    end

  end

  def edit
    @user = User.find(params[:id])  
  end

  def update
    @user = User.find(params[:id])  
    @user.update(user_params)
    redirect_to(@user)
  end

  def logout
    reset_session
    redirect_to :root
    #render :nothing => true
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @urls = Url.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def ini_uri
    'http://sho.di/'
  end

  def current_user
    if session[:id]
      User.find(session[:id])
    end
  end

   # Regresa true si el current_user existe y false de otra manera 
  def logged_in?
    if current_user
      true
    else
      false
    end
  end
  
end

app/helpers/urls_helper.rb
module UrlsHelper
end

app/helpers/users_helper.rb
module UsersHelper

 

end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsBitly</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<h1 class="welcome">Welcome to Bitly on Rails <%= ini_uri  %></h1>
<div class="contenedor">
<%= yield %>
</div>
</body>
</html>

app/views/urls/_new_form.html.erb
<%= form_for @url, remote: :true do |f| %>
  <%= f.text_field :long_url, placeholder: "Ingresa long url" ,:class => "long_input"  %>

  <%= f.submit "Crear Short Url" %>
<% end %>

<div id="error_url"></div>

app/views/urls/create.js.erb
//console.log('<%= @new_url.errors %>')

<% if @new_url.errors %>
  console.log("error")
  $("#error_url").html("<br><div style='color:red;'>La url que ingresaste no es valida</div><br>");
  console.log("error")
<% else %>
  $("#error_url").html("<br><div style='color:red;'>lala/div><br>");
<% end %>

// https://www.alfajango.com/blog/rails-js-erb-remote-response-not-executing/

app/views/urls/new.js.erb
$("#new_link").hide().after('<%= j render("new_form") %>')

app/views/users/edit.html.erb
<%= form_for @user do |f| %>

  Nombre:
  <%= f.text_field :name, placeholder: "Ingresa tu nombre" %><br><br>

   Correo:
  <%= f.text_field :email, placeholder: "Ingresa tu correo" %><br><br>

   Contraseña:
  <%= f.password_field :password, placeholder: "Ingresa nueva contraseña" %><br><br>

  <%= f.submit "Actualizar" %>
<% end %>

app/views/users/login.html.erb
<br>
<div>Ingresa tu Usuario para iniciar sesión:</div>
<br>
<div class="form-container">


  <%= form_for @user, html: { autocomplete: "off" }, url: {action: "authenticate"} , method: :post do |f| %>
    Ingresa tu correo:<br><br>
    <%= f.text_field :email %><br><br>
    Ingresa tu password:<br><br>
    <%= f.password_field :password %><br><br>
    <%= f.submit "Ingresar" %>
  <% end %>

<br>
  <% if @error %>
    <div class="error"><%= @error %></div>
  <% end %>

</div>

<%= link_to 'Index', root_path %> 

app/views/users/new.html.erb
<div class="form-container">

<%= form_for @user do |f| %>

  Nombre:
  <%= f.text_field :name, placeholder: "Ingresa tu nombre" %><br><br>

   Correo:
  <%= f.text_field :email, placeholder: "Ingresa tu correo" %><br><br>

   Contraseña:
  <%= f.password_field :password, placeholder: "Ingresa tu contraseña" %><br><br>

  <%= f.submit "Crear cuenta" %>
<% end %>
  
  <% if @errors %>
    <% @errors.each do |attribute, message| %>
      <br>
      <div class="error"><%= message.join %></div>
    <% end %>
  <% end %>

</div>
<br>
<%= link_to 'Index', root_path %> 

app/views/users/show.html.erb
<h2>Bienvenido a tu Perfil: <%= @user.name %></h2>

<br>
<%= link_to 'Crear nueva short url', new_url_path, remote: :true, id: 'new_link' %>
<br><br>

<div>Ultimas Urls Creadas: </div> 

<div id="urls-contenedor">
  <% @urls_user.each do |u|%>
    <p><%= u.long_url %>
      <br>
      <% @url = u %>
      <span><%= link_to "#{ini_uri + u.short_url}", visitlong_path(u.id), 'data-turbolinks' => false %>

      </span> &nbsp&nbsp&nbsp&nbsp
      <span>Visitas: <%= u.visits %></span>
    </p>
  <% end %>
</div>

<br>
<%= link_to 'Cambiar mis datos', edit_user_path(@user) %>
<br><br>
<%= link_to 'Index', root_path %>
<br><br>
<%= link_to 'Cerrar sesión', logout_path %> 

app/views/welcome/index.html.erb
<h3>Estas son las últimas urls creadas:</h3>

<br>
<%= link_to 'Crear nueva short url', new_url_path, remote: :true, id: 'new_link' %>
<br><br>

<% @urls.each do |u| %>

  <p><%= u.long_url %> <br>

    <span><span><%= link_to "#{ini_uri + u.short_url}", visitlong_path(u.id), 'data-turbolinks' => false %></span>&nbsp&nbsp&nbsp&nbsp&nbsp

    <span>Visitas: <%= u.visits%></span><br>

    <% user_id = u.user_id %>
    <% if user_id == nil %>
      <span style="color:#E71D36;">Autor: Desconocido </span>
    <% else %>
      <span style="color:#E71D36;">Autor: <%= User.find(user_id).name %> </span>
    <% end %>
  </p>

<% end %>

<% if current_user %>
  <%= link_to 'Ir a mi perfil', current_user %> 
<% else %>

  <%= link_to 'Login', login_path %> 
  <br><br>
  No tienes cuenta? <%= link_to 'Registrarme', new_user_path %> 

<% end %>